TextLoader

In [6]:
from langchain.document_loaders import TextLoader


In [ ]:
loader = TextLoader('example.txt')
data = loader.load()


[Document(metadata={'source': 'example.txt'}, page_content='Indian batting stalwart Rohit Sharma once again showed why he is loved not just for his cricket, but also for his humble nature.\nAfter Mumbai’s opening match in the Vijay Hazare Trophy on Wednesday, a young fan tried to touch Rohit’s feet as a mark of respect.')]


In [3]:
data[0]

Document(metadata={'source': 'example.txt'}, page_content='Indian batting stalwart Rohit Sharma once again showed why he is loved not just for his cricket, but also for his humble nature.\nAfter Mumbai’s opening match in the Vijay Hazare Trophy on Wednesday, a young fan tried to touch Rohit’s feet as a mark of respect.')

In [4]:
data[0].page_content

'Indian batting stalwart Rohit Sharma once again showed why he is loved not just for his cricket, but also for his humble nature.\nAfter Mumbai’s opening match in the Vijay Hazare Trophy on Wednesday, a young fan tried to touch Rohit’s feet as a mark of respect.'

In [5]:
data[0].metadata

{'source': 'example.txt'}

csv loader

In [ ]:
from langchain.document_loaders import CSVLoader


In [ ]:
loader = CSVLoader('placement.csv')
data = loader.load()

[Document(metadata={'source': 'placement.csv', 'row': 0}, page_content='cgpa: 8.14\nresume_score: 6.52\nplaced: 1'),
 Document(metadata={'source': 'placement.csv', 'row': 1}, page_content='cgpa: 6.17\nresume_score: 5.17\nplaced: 0'),
 Document(metadata={'source': 'placement.csv', 'row': 2}, page_content='cgpa: 8.27\nresume_score: 8.86\nplaced: 1'),
 Document(metadata={'source': 'placement.csv', 'row': 3}, page_content='cgpa: 6.88\nresume_score: 7.27\nplaced: 1'),
 Document(metadata={'source': 'placement.csv', 'row': 4}, page_content='cgpa: 7.52\nresume_score: 7.3\nplaced: 1'),
 Document(metadata={'source': 'placement.csv', 'row': 5}, page_content='cgpa: 8.77\nresume_score: 6.19\nplaced: 1'),
 Document(metadata={'source': 'placement.csv', 'row': 6}, page_content='cgpa: 5.34\nresume_score: 7.09\nplaced: 0'),
 Document(metadata={'source': 'placement.csv', 'row': 7}, page_content='cgpa: 6.56\nresume_score: 6.29\nplaced: 0'),
 Document(metadata={'source': 'placement.csv', 'row': 8}, page_co

In [14]:
data[0].metadata

{'source': 'placement.csv', 'row': 0}

In [15]:
data[0].page_content

'cgpa: 8.14\nresume_score: 6.52\nplaced: 1'

In [16]:
data

[Document(metadata={'source': 'placement.csv', 'row': 0}, page_content='cgpa: 8.14\nresume_score: 6.52\nplaced: 1'),
 Document(metadata={'source': 'placement.csv', 'row': 1}, page_content='cgpa: 6.17\nresume_score: 5.17\nplaced: 0'),
 Document(metadata={'source': 'placement.csv', 'row': 2}, page_content='cgpa: 8.27\nresume_score: 8.86\nplaced: 1'),
 Document(metadata={'source': 'placement.csv', 'row': 3}, page_content='cgpa: 6.88\nresume_score: 7.27\nplaced: 1'),
 Document(metadata={'source': 'placement.csv', 'row': 4}, page_content='cgpa: 7.52\nresume_score: 7.3\nplaced: 1'),
 Document(metadata={'source': 'placement.csv', 'row': 5}, page_content='cgpa: 8.77\nresume_score: 6.19\nplaced: 1'),
 Document(metadata={'source': 'placement.csv', 'row': 6}, page_content='cgpa: 5.34\nresume_score: 7.09\nplaced: 0'),
 Document(metadata={'source': 'placement.csv', 'row': 7}, page_content='cgpa: 6.56\nresume_score: 6.29\nplaced: 0'),
 Document(metadata={'source': 'placement.csv', 'row': 8}, page_co

In [17]:
len(data)

100

In [18]:
!pip install unstructured libmagic python-magic-bin

  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
     ---------------------------------------- 0.0/981.5 kB ? eta -:--:--
     ---------------------------------------- 0.0/981.5 kB ? eta -:--:--
     ---------------------------------------- 0.0/981.5 kB ? eta -:--:--
     ---------- ----------------------------- 262.1/981.5 kB ? eta -:--:--
     ------------------- ---------------- 524.3/981.5 kB 985.5 kB/s eta 0:00:01
     ---------------------------------------- 981.5/981.5 kB 1.4 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
 

In [19]:
from langchain.document_loaders import UnstructuredURLLoader

In [ ]:
loader = UnstructuredURLLoader(urls=['https://en.wikipedia.org/wiki/Artificial_intelligence',
                             'https://en.wikipedia.org/wiki/Machine_learning'
                             ])

In [22]:
data = loader.load()

In [23]:
data[0]

Document(metadata={'source': 'https://en.wikipedia.org/wiki/Artificial_intelligence'}, page_content='Please set a user-agent and respect our robot policy https://w.wiki/4wJS. See also https://phabricator.wikimedia.org/T400119.')

In [24]:
len(data)

2

text spliting

In [39]:
text = """ Artificial intelligence (AI) is the capability of computational systems to perform tasks typically associated with human intelligence, such as learning, reasoning, problem-solving, perception, and decision-making. It is a field of research in computer science that develops and studies methods and software that enable machines to perceive their environment and use learning and intelligence to take actions that maximize their chances of achieving defined goals.[1]

High-profile applications of AI include advanced web search engines (e.g., Google Search); recommendation systems (used by YouTube, Amazon, and Netflix); virtual assistants (e.g., Google Assistant, Siri, and Alexa); autonomous vehicles (e.g., Waymo); generative and creative tools (e.g., language models and AI art); and superhuman play and analysis in strategy games (e.g., chess and Go). However, many AI applications are not perceived as AI: "A lot of cutting edge AI has filtered into general applications, often without being called AI because once something becomes useful enough and common enough it's not labeled AI anymore."[2][3]

Various subfields of AI research are centered around particular goals and the use of particular tools. The traditional goals of AI research include learning, reasoning, knowledge representation, planning, natural language processing, perception, and support for robotics.[a] To reach these goals, AI researchers have adapted and integrated a wide range of techniques, including search and mathematical optimization, formal logic, artificial neural networks, and methods based on statistics, operations research, and economics.[b] AI also draws upon psychology, linguistics, philosophy, neuroscience, and other fields.[4] Some companies, such as OpenAI, Google DeepMind and Meta,[5] aim to create artificial general intelligence (AGI) – AI that can complete virtually any cognitive task at least as well as a human"""

In [ ]:
text[:100] 

#this is mostly used for testing purpose, it causes issues of cutting the word in the middle

'Artificial intelligence (AI) is intelligence—perceiving, synthesizing, and inferring information—dem'

In [30]:

chunks = []

s = ""
for word in text:
    s += word + " "
    if len(s) > 100:
        chunks.append(s)
        s = ""

chunks.append(s)  # append any remaining text

In [31]:
chunks

['A r t i f i c i a l   i n t e l l i g e n c e   ( A I )   i s   i n t e l l i g e n c e — p e r c e i ',
 'v i n g ,   s y n t h e s i z i n g ,   a n d   i n f e r r i n g   i n f o r m a t i o n — d e m o n ',
 's t r a t e d   b y   m a c h i n e s ,   a s   o p p o s e d   t o   i n t e l l i g e n c e   d i s ',
 'p l a y e d   b y   n o n - h u m a n   a n i m a l s   a n d   h u m a n s .   E x a m p l e   t a s ',
 'k s   i n   w h i c h   t h i s   i s   d o n e   i n c l u d e   s p e e c h   r e c o g n i t i o n ',
 ',   c o m p u t e r   v i s i o n ,   t r a n s l a t i o n   b e t w e e n   ( n a t u r a l )   l a ',
 'n g u a g e s ,   a s   w e l l   a s   o t h e r   m a p p i n g s   o f   i n p u t s .   A I   a p ',
 'p l i c a t i o n s   i n c l u d e   a d v a n c e d   w e b   s e a r c h   e n g i n e s   ( e . g ',
 '. ,   G o o g l e ) ,   r e c o m m e n d a t i o n   s y s t e m s   ( u s e d   b y   Y o u T u b e ',
 ',   A m a z o n ,   a n d   N e t f

In [44]:
from langchain.text_splitter import CharacterTextSplitter


splitter = CharacterTextSplitter(
    separator= "\n",
    chunk_size= 200,
    chunk_overlap= 0,
)

chunks = splitter.split_text(text)
len(chunks)

Created a chunk of size 467, which is longer than the specified 200
Created a chunk of size 639, which is longer than the specified 200


3

In [45]:
chunks

['Artificial intelligence (AI) is the capability of computational systems to perform tasks typically associated with human intelligence, such as learning, reasoning, problem-solving, perception, and decision-making. It is a field of research in computer science that develops and studies methods and software that enable machines to perceive their environment and use learning and intelligence to take actions that maximize their chances of achieving defined goals.[1]',
 'High-profile applications of AI include advanced web search engines (e.g., Google Search); recommendation systems (used by YouTube, Amazon, and Netflix); virtual assistants (e.g., Google Assistant, Siri, and Alexa); autonomous vehicles (e.g., Waymo); generative and creative tools (e.g., language models and AI art); and superhuman play and analysis in strategy games (e.g., chess and Go). However, many AI applications are not perceived as AI: "A lot of cutting edge AI has filtered into general applications, often without be

In [47]:
for chunk in chunks:
    print(len(chunk))

466
639
813


In [48]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

In [49]:
r_splitter = RecursiveCharacterTextSplitter(
    separators=["\n\n", "\n", " "],
    chunk_size=200,
    chunk_overlap=0,
    )

chunks = r_splitter.split_text(text)
len(chunks)

12

In [50]:
for chunk in chunks:
    print(len(chunk))

196
197
71
197
191
199
49
194
193
196
199
27


In [52]:
chunks = text.split("\n\n")
for chunk in chunks:
    print(len(chunk))

467
639
813


In [53]:
first_split = chunks[0]
first_split

' Artificial intelligence (AI) is the capability of computational systems to perform tasks typically associated with human intelligence, such as learning, reasoning, problem-solving, perception, and decision-making. It is a field of research in computer science that develops and studies methods and software that enable machines to perceive their environment and use learning and intelligence to take actions that maximize their chances of achieving defined goals.[1]'

In [54]:
second_split = first_split.split('\n')
second_split

[' Artificial intelligence (AI) is the capability of computational systems to perform tasks typically associated with human intelligence, such as learning, reasoning, problem-solving, perception, and decision-making. It is a field of research in computer science that develops and studies methods and software that enable machines to perceive their environment and use learning and intelligence to take actions that maximize their chances of achieving defined goals.[1]']

vector database

In [1]:
!pip  install faiss-cpu
!pip install sentence_transformers

   ---------------------------------------- 0.0/18.7 MB ? eta -:--:--
    --------------------------------------- 0.3/18.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/18.7 MB 1.9 MB/s eta 0:00:10
   -- ------------------------------------- 1.0/18.7 MB 1.9 MB/s eta 0:00:10
   -- ------------------------------------- 1.3/18.7 MB 1.8 MB/s eta 0:00:10
   --- ------------------------------------ 1.6/18.7 MB 1.8 MB/s eta 0:00:10
   ---- ----------------------------------- 2.1/18.7 MB 1.7 MB/s eta 0:00:10
   ----- ---------------------------------- 2.4/18.7 MB 1.7 MB/s eta 0:00:10
   ------ --------------------------------- 2.9/18.7 MB 1.8 MB/s eta 0:00:09
   ------ --------------------------------- 3.1/18.7 MB 1.8 MB/s eta 0:00:09
   ------- -------------------------------- 3.7/18.7 MB 1.9 MB/s eta 0:00:09
   -------- ------------------------------- 4.2/18.7 MB 1.9 MB/s eta 0:00:08
   ---------- ----------------------------- 4.7/18.7 MB 1.9 MB/s eta 0:00:08
   ----------

In [1]:
import pandas as pd

pd.set_option('display.max_colwidth', 100)


In [2]:
df = pd.read_csv("final_movies.csv")

df.shape

(4809, 3)

In [3]:
df

movie_id                                     title  \
0        19995                                    Avatar   
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4804      9367                               El Mariachi   
4805     72766                                 Newlyweds   
4806    231617                 Signed, Sealed, Delivered   
4807    126186                          Shanghai Calling   
4808     25975                         My Date with Drew   

                                                                                                     tags  
0     in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, ...  
1     captain barbossa, long believed to be dead, has come back to life and is headed to the edge of t...  
2     a cryptic message from bond’s past sends him on a trail to uncover a sinister organization. whil...  
3     following the death of district attorney harvey dent, batman assumes responsibility for dent's c...  
4     john carter is a war-weary, former military captain who's inexplicably transported to the myster...  
...                                                                                                   ...  
4804  el mariachi just wants to play his guitar and carry on the family tradition. unfortunately, the ...  
4805  a newlywed couple's honeymoon is upended by the arrivals of their respective sisters. comedy rom...  
4806  "signed, sealed, delivered" introduces a dedicated quartet of civil servants in the dead letter ...  
4807  when ambitious new york attorney sam is sent to shanghai on assignment, he immediately stumbles ...  
4808  ever since the second grade when he first saw her in e.t. the extraterrestrial, brian herzlinger...  

[4809 rows x 3 columns]

In [12]:
!pip uninstall keras -y
!pip install tf-keras


Found existing installation: keras 3.10.0
Uninstalling keras-3.10.0:
  Successfully uninstalled keras-3.10.0
  Using cached keras-3.10.0-py3-none-any.whl.metadata (6.0 kB)
Using cached keras-3.10.0-py3-none-any.whl (1.4 MB)


In [4]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer('all-mpnet-base-v2')
vector = encoder.encode(df.tags)

vector.shape


c:\Users\nikhi\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


(4809, 768)

In [5]:
dim = vector.shape[1]
dim

768

In [6]:
import faiss

index = faiss.IndexFlatIP(dim)
index

<faiss.swigfaiss_avx2.IndexFlatIP; proxy of <Swig Object of type 'faiss::IndexFlatIP *' at 0x0000018AC5E0A810> >

In [7]:
index.add(vector)

In [35]:
search_query = "an apple a day keeps the doctor away"
vec = encoder.encode(search_query)

vec.shape

(768,)

In [36]:
import numpy as np
svec = np.array(vec).reshape(1, -1)  # Reshape to 2D array with one row
svec.shape

(1, 768)

In [37]:
vec

array([ 1.77043136e-02,  7.70549998e-02, -1.25192413e-02, -1.39336148e-03,
        5.92108816e-03, -1.42679159e-02, -4.72584032e-02,  3.91954929e-03,
        4.41600867e-02,  3.09807677e-02,  9.15983468e-02,  2.02603433e-02,
       -2.16004848e-02,  1.33208549e-02, -4.14275937e-02,  4.16395590e-02,
        4.37019207e-02,  6.06423570e-03,  2.21780222e-02, -1.94715634e-02,
       -3.44190449e-02,  3.79219875e-02,  5.27907768e-03,  2.22010948e-02,
       -1.11636976e-02, -2.53351294e-02,  7.79389217e-02,  3.47347707e-02,
        1.20056299e-02, -6.52653500e-02, -4.83941361e-02, -3.03445403e-02,
       -6.99562579e-02, -2.53461916e-02,  1.78119137e-06,  1.50222424e-02,
        2.15191673e-02,  2.21124496e-02, -8.38034526e-02,  3.70956119e-03,
       -2.21117977e-02, -8.53062496e-02,  6.44870917e-04,  1.62597820e-02,
       -1.88166052e-02,  3.99218425e-02, -3.13138962e-02,  2.47449353e-02,
       -7.98756257e-03,  6.11144677e-02, -1.47846313e-02,  4.10902612e-05,
        1.20446933e-02,  

In [38]:
svec

array([[ 1.77043136e-02,  7.70549998e-02, -1.25192413e-02,
        -1.39336148e-03,  5.92108816e-03, -1.42679159e-02,
        -4.72584032e-02,  3.91954929e-03,  4.41600867e-02,
         3.09807677e-02,  9.15983468e-02,  2.02603433e-02,
        -2.16004848e-02,  1.33208549e-02, -4.14275937e-02,
         4.16395590e-02,  4.37019207e-02,  6.06423570e-03,
         2.21780222e-02, -1.94715634e-02, -3.44190449e-02,
         3.79219875e-02,  5.27907768e-03,  2.22010948e-02,
        -1.11636976e-02, -2.53351294e-02,  7.79389217e-02,
         3.47347707e-02,  1.20056299e-02, -6.52653500e-02,
        -4.83941361e-02, -3.03445403e-02, -6.99562579e-02,
        -2.53461916e-02,  1.78119137e-06,  1.50222424e-02,
         2.15191673e-02,  2.21124496e-02, -8.38034526e-02,
         3.70956119e-03, -2.21117977e-02, -8.53062496e-02,
         6.44870917e-04,  1.62597820e-02, -1.88166052e-02,
         3.99218425e-02, -3.13138962e-02,  2.47449353e-02,
        -7.98756257e-03,  6.11144677e-02, -1.47846313e-0

In [39]:
distances, I = index.search(svec, k=2)  # Search for the top 5 most similar vectors

In [40]:
I

array([[ 905, 4623]])

In [41]:
df.loc[I[0]]

movie_id                   title  \
905      10312             Patch Adams   
4623     73981  Ayurveda: Art of Being   

                                                                                                     tags  
905   meet patch adams, a doctor who doesn't look, act or think like any doctor you've met before. for...  
4623  ayurveda is a science of life and a healing art, where body, mind and spirit are given equal imp...

In [25]:
distances

array([[0.7056124, 0.5575791]], dtype=float32)

movie_id   title  \
0     19995  Avatar   
0     19995  Avatar   

                                                                                                  tags  
0  in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, ...  
0  in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, ...

In [27]:
search_query

'adventure comedy'

RetrivalQAwithSourcesChain